version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "node-packages"
          paths:
            - /src/node_modules
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
        keys:
          - "node-packages"
  # analyze:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - restore_cache:
  #       keys:
  #         - "node-packages"
  #     - run: npm i
  #     - run: npm run audit

workflows:
  my_workflow:
    jobs:
      - build
      - test:
        jobRef:
          requires:
            - build
      # - analyze:
      #   jobRef:
      #     requires:
      #       - test